name: Shotter
options:
  bundleIdPrefix: com.amrit
  deploymentTarget:
    macOS: "12.3"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "12.3"

targets:
  Shotter:
    type: application
    platform: macOS
    sources:
      - path: Shotter
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amrit.Shotter
        PRODUCT_NAME: Shotter
        INFOPLIST_FILE: Shotter/Info.plist
        CODE_SIGN_ENTITLEMENTS: Shotter/Shotter.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: Shotter/Shotter.entitlements
